# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14GvARqRkexP8jelzJQ62W5hA4A1dpinm
"""

import streamlit as st
import torch
import pickle
import numpy as np
from transformers import (
    RobertaTokenizer,
    RobertaForSequenceClassification,
    T5Tokenizer,
    T5ForConditionalGeneration
)

# ============================================================
#         Page Config
# ============================================================

st.set_page_config(
    page_title="News Article Analyser",
    page_icon="📰",
    layout="wide"
)

st.title("📰 News Article Analyser")
st.markdown("Enter a news article to get **topic labels** and a **3-sentence summary**.")
st.divider()


# ============================================================
#         Load Models
# ============================================================

@st.cache_resource
def load_classification_model():
    with open("models/mlb.pkl", "rb") as f:
        mlb = pickle.load(f)

    with open("models/best_thresholds_roberta.pkl", "rb") as f:
        thresholds = pickle.load(f)

    tokenizer = RobertaTokenizer.from_pretrained("roberta-base")

    model = RobertaForSequenceClassification.from_pretrained(
        "roberta-base",
        num_labels=len(mlb.classes_),
        problem_type="multi_label_classification"
    )
    model.load_state_dict(
        torch.load("models/model_roberta_v1.pt", map_location="cpu")
    )
    model.eval()

    return model, tokenizer, mlb, thresholds


@st.cache_resource
def load_summarisation_model():
    tokenizer = T5Tokenizer.from_pretrained("t5-small")
    model     = T5ForConditionalGeneration.from_pretrained("t5-small")
    model.eval()
    return model, tokenizer


# ============================================================
#         Classification Function
# ============================================================

def classify_article(headline, body, model, tokenizer, mlb, thresholds):
    text     = headline + " " + body
    encoding = tokenizer(
        text,
        max_length=512,
        padding="max_length",
        truncation=True,
        return_tensors="pt"
    )

    with torch.no_grad():
        outputs = model(**encoding)
        probs   = torch.sigmoid(outputs.logits).numpy()[0]

    predicted_labels = []
    for i, (prob, thresh) in enumerate(zip(probs, thresholds)):
        if prob >= thresh:
            predicted_labels.append(mlb.classes_[i])

    return predicted_labels, probs


# ============================================================
#         Summarisation Function
# ============================================================

def summarise_article(body, model, tokenizer):
    input_text = "summarize: " + body
    input_ids  = tokenizer(
        input_text,
        max_length=512,
        truncation=True,
        return_tensors="pt"
    ).input_ids

    with torch.no_grad():
        output_ids = model.generate(
            input_ids,
            max_length=128,
            min_length=30,
            num_beams=4,
            length_penalty=2.0,
            early_stopping=True
        )

    return tokenizer.decode(output_ids[0], skip_special_tokens=True)


# ============================================================
#         UI
# ============================================================

# Load models
with st.spinner("Loading models..."):
    clf_model, clf_tokenizer, mlb, thresholds = load_classification_model()
    sum_model, sum_tokenizer                  = load_summarisation_model()

st.success("✅ Models loaded!")

# Input
col1, col2 = st.columns([1, 1])

with col1:
    headline = st.text_input(
        "📰 Article Headline",
        placeholder="Enter headline here..."
    )

with col2:
    st.write("")

body = st.text_area(
    "📄 Article Body",
    placeholder="Enter article body here...",
    height=250
)

# Analyse button
if st.button("🔍 Analyse Article", type="primary"):

    if not headline or not body:
        st.warning("⚠️ Please enter both headline and body!")

    else:
        with st.spinner("Analysing..."):

            # Classification
            labels, probs = classify_article(
                headline, body,
                clf_model, clf_tokenizer, mlb, thresholds
            )

            # Summarisation
            summary = summarise_article(body, sum_model, sum_tokenizer)

        st.divider()

        # Results
        col1, col2 = st.columns([1, 1])

        with col1:
            st.subheader("🏷️ Predicted Topics")
            if labels:
                for label in labels:
                    st.success(f"✅ {label}")
            else:
                st.warning("No labels predicted!")

            st.subheader("📊 Label Probabilities")
            for cls, prob in zip(mlb.classes_, probs):
                st.progress(
                    float(prob),
                    text=f"{cls}: {prob:.2f}"
                )

        with col2:
            st.subheader("📝 Article Summary")
            st.info(summary)